language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
- pip install coveralls
script:
- coverage run --source=gitea_client setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: unfoldingword
  password:
    secure: Zm+QzSxjTVG3qOR92fdImmdeIjHK11+lTeSg1ChbEJbq/pZw2O6RDSt2w8pafJUYRiyzjz6EYtRLZU/fCMP7qcO8NSD4m3adBVPKpaG515AnRjzYdkYTubNy2dHzU10bE4qkJsd0kbXSZwUdvUhoI6ZLu/IoYnlcD9tCAFaqWOS8fpWcFfzG9yB+SCOOz+O58BZdNmhs3o/uoZWUoPrs8/ux+ek3ghrJrkGJ4cVwLKGDpHiHmsKUqA3LEVQxvRWaiNnb9f7ASXaYyIG9nfBor145Xn3g7eaXV1ideFTFviog5+7CMaqIQExuJQX/X2g3zx4SqaPdE1nDaIJ4P8cclmVTR4kxwLQ4txCI7RwttuXojGhXwG4LO0A7IcWHHz6hqNhUhnTXvd7sVlx6YCjChRycpF1ttrsH98R+LcmIIwsid2lmtILHt9slO1vwXKqTt1VQaOYTHKnXYcTBIS0T7Srnl/sMnn/XkN8W/Wm7jWeMCtB7Ui59w7SLp/ghoMcbyLm3OI/JHkEY0jUmRcYkMp0dv3zuJCm4WE7kLd2I9R/sf3MkvbqchpHDf3vcoaPjm7I0forkCeXoxis+B+GAb1P6NVQhfuj9/vIZWowfWs9aOY81dZMp/tLg58btx+yxGdXQOiPcDI75Q720SirqjFl+UDku8Y+1nBbem2/gvSA=
  on:
    tags: true
  distributions: sdist bdist_wheel
